//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneReworked.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSVP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSVP()
        {
            this.FoodMenus = new HashSet<FoodMenu>();
        }
    
        public string Name { get; set; }
        public string Attending { get; set; }
        public Nullable<int> GuestNumber { get; set; }
        public string FoodItems { get; set; }
        public string Allergies { get; set; }
        public string Comments { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodMenu> FoodMenus { get; set; }
    }
}
